# nps_2013/2014/2015

# nps_2013_t30
# 15 columns
names=['SPEC_ID_SNO','LN_NO','CZ_ITEM_CD','DIV_TY_CD','DIV_CD','SP1_SP2_TP_CD','FQ1_MDCT_QTY','DY1_MDCT_QTY','DY1_INJC_QTY_EXEC_FQ','TOT_INJC_DDCNT_EXEC_FQ',
       'TOT_USE_QTY_OR_EXEC_FQ', 'UNPRC', 'AMT', 'ADDC_ADT_AMT', 'GNL_NM_CD']

# nps_2013_t40
# 5 columns
names=['SPEC_ID_SNO', 'SICK_SNO', 'SICK_DGSBJT_CD', 'SICK_CD', 'DMD_DGSBJT_CD']

# nps_2013_t53
# 10 columns
names=['SPEC_ID_SNO','LN_NO','PRSCP_GRANT_NO','FQ1_MDCT_QTY','DY1_MDCT_QTY','TOT_INJC_DDCNT_EXEC_FQ','TOT_USE_QTY_OR_EXEC_FQ','UNPRC','AMT','GNL_NM_CD']

# nps_2014_t30
# 15 columns
names=['SPEC_ID_SNO', 'LN_NO', 'CZ_ITEM_SNO', 'DIV_TY_CD', 'DIV_CD', 'SP1_SP2_TP_CD', 'FQ1_MDCT_TP_CD', 'DY1_MDCT_QTY', 'DY1_INJC_QTY_EXEC_FQ', 
           'TOT_INJC_DDCNT_EXEC_FQ', 'TOT_USE_QTY_OR_EXEC_FQ', 'UNPRC', 'AMT', 'ADDC_ADT_AMT', 'GNL_NM_CD']

# nps_2014_t40
# 5 columns
names=['SPEC_ID_SNO', 'SICK_SNO', 'SICK_DGSBJT_CD', 'SICK_CD', 'DMD_DGSBJT_CD']

# nps_2014_t53
# 10 columns
names=['SPEC_ID_SNO', 'LN_NO', 'PRSCP_GRANT_NO', 'FQ1_MDCT_QTY', 'DY1_MDCT_QTY', 'TOT_INJC_DDCNT_EXEC_FQ', 'TOT_USE_QTY_EXEC_FQ', 'UNPRC', 'AMT', 'GNL_NM_CD']

# nps_2013/2014/2015_ykiho
# 13 columns
names=['YID', 'DATE', 'SIDO_CD', 'CL_CD', 'ORG_DF', 'BED_GRADE',
    'PER_50BED_DOCTOR', 'PER_50BED_DENTAL', 'PER_50BED_ORIENTAL', 'PER_50BED_NURSE', 'CT', 'MRI', 'PET']
